//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroidvaniaDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetroidvaniaDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;spritesheet&gt;
        ///    &lt;sprites image=&quot;assets/player-idle&quot;&gt;
        ///        &lt;animation title=&quot;PlayerIdle&quot; delay=&quot;3&quot;&gt;
        ///            &lt;cut w=&quot;20&quot; x=&quot;29&quot; y=&quot;24&quot; h=&quot;40&quot;/&gt;
        ///            &lt;cut w=&quot;18&quot; x=&quot;110&quot; y=&quot;25&quot; h=&quot;39&quot;/&gt;
        ///            &lt;cut w=&quot;16&quot; x=&quot;191&quot; y=&quot;26&quot; h=&quot;38&quot;/&gt;
        ///            &lt;cut w=&quot;18&quot; x=&quot;270&quot; y=&quot;25&quot; h=&quot;39&quot;/&gt;
        ///        &lt;/animation&gt;
        ///    &lt;/sprites&gt;
        ///    &lt;sprites image=&quot;assets/player-run&quot;&gt;
        ///        &lt;animation title=&quot;PlayerRun&quot; delay=&quot;3&quot;&gt;
        ///            &lt;cut w=&quot;21&quot; x=&quot;29&quot; y=&quot;30&quot; h=&quot;34&quot;/&gt;
        ///            &lt;cut w=&quot;22&quot; x=&quot;110&quot; y=&quot;28&quot; h=&quot;36&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerAnimation {
            get {
                return ResourceManager.GetString("PlayerAnimation", resourceCulture);
            }
        }
    }
}
